
name: routine_planner
description: Routine Planner completo com Firebase simulado e lógica de planos
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
